#!/bin/bash
cd ~
watched_files=".zshrc .bashrc .gitconfig .bash_profile .bash_aliases .gitignore_global .composer/composer.json"

if [ "-b" = "$1" ]
then
    for tmpf in $watched_files
    do
        if [ -f ~/$tmpf ]
        then
            mkdir -p `dirname ~/dotfiles/$tmpf`
            cp -vrf ~/$tmpf ~/dotfiles/$tmpf
        fi
    done
    ls -lhA ~/dotfiles
elif [ "-s" = "$1" ]
then
    for tmpf in $watched_files
    do
        if [ -f ~/dotfiles/$tmpf ]
        then
            mkdir -p `dirname ~/$tmpf`
            cp -vrf ~/dotfiles/$tmpf ~/$tmpf
        fi
    done
    ls -lhA ~
else
    echo Supported options:
    echo   -b backup
    echo   -s setup
fi
