#!/bin/bash
watched_files=".gitconfig .bash_profile .bash_aliases"

if [ "-b" = "$1" ]
then
    for tmpf in $watched_files
    do
        if [ -f ~/$tmpf ]
        then
            cp -vf ~/$tmpf ~/dotfiles/$tmpf
        fi
    done
    ls -lhA ~/dotfiles
elif [ "-s" = "$1" ]
then
    for tmpf in $watched_files
    do
        if [ -f ~/dotfiles/$tmpf ]
        then
            cp -vf ~/dotfiles/$tmpf ~/$tmpf
        fi
    done
    ls -lhA ~
else
    echo Supported options:
    echo   -b backup
    echo   -s setup
fi
